import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  editorialText: string = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue porttitor quam eu dignissim. Morbi fermentum eget ex ut ullamcorper. Pellentesque sit amet erat a est auctor gravida. Nulla egestas commodo ullamcorper. Proin ornare tempus ante in ultrices. Proin feugiat, dolor a ultrices iaculis, mi risus semper orci, vitae lobortis est mi at libero. Donec imperdiet elit nec quam iaculis, eu vehicula diam lacinia. Nam lacinia ex et arcu tincidunt, et iaculis mi euismod.</p>

  <p>Praesent maximus odio lobortis euismod viverra. Aliquam hendrerit tempor purus eget interdum. Aliquam erat volutpat. Vestibulum efficitur sem ut dui faucibus, vitae ultrices justo viverra. Ut nunc erat, dignissim eget ipsum quis, laoreet vehicula urna. Quisque eu efficitur felis. Nulla auctor sapien et eleifend interdum. Praesent at dolor felis. Sed nec erat a mauris cursus eleifend et in orci. Nam ut erat sit amet ante ullamcorper ultricies. Aenean faucibus ac quam a tempus. Pellentesque ornare commodo massa et vestibulum. Ut ac massa ut risus bibendum laoreet fermentum quis ligula. In pretium pulvinar dui eget pulvinar.</p>
  
  <p>Praesent quis eros id leo ullamcorper vulputate. Etiam at tortor convallis, imperdiet tortor a, euismod velit. Aenean mattis leo sed purus pulvinar lobortis. Vestibulum mi tellus, luctus ac consequat et, mollis at est. Aliquam et orci tellus. Quisque pretium feugiat nibh at malesuada. Nulla id est non lorem cursus porttitor.</p>`

  articleSummaryText: string =  `A man must protect his family from James Bond, played by Timothy Dalton. Basically Braveheart set against the background of the American revolution, this film consectetur adipiscing elit. Nunc congue porttitor quam eu dignissim. Morbi fermentum eget ex ut ullamcorper. Pellentesque sit amet erat a est auctor gravida. Nulla egestas commodo ullamcorper. Proin ornare tempus ante in ultrices. Proin feugiat, dolor a ultrices iaculis, mi risus semper orci, vitae lobortis est mi at libero. Donec imperdiet elit nec quam iaculis, eu vehicula diam lacinia. Nam lacinia ex et arcu tincidunt, et iaculis mi euismod.`;

  reviewTextGood: string = `GOOD: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue porttitor quam eu dignissim. Morbi fermentum eget ex ut ullamcorper. Pellentesque sit amet erat a est auctor gravida. Nulla egestas commodo ullamcorper. Proin ornare tempus ante in ultrices. Proin feugiat, dolor a ultrices iaculis, mi risus semper orci, vitae lobortis est mi at libero. Donec imperdiet elit nec quam iaculis, eu vehicula diam lacinia. Nam lacinia ex et arcu tincidunt, et iaculis mi euismod.`

  reviewTextBad: string = `<p>BAD: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc congue porttitor quam eu dignissim. Morbi fermentum eget ex ut ullamcorper. Pellentesque sit amet erat a est auctor gravida. Nulla egestas commodo ullamcorper. Proin ornare tempus ante in ultrices. Proin feugiat, dolor a ultrices iaculis, mi risus semper orci, vitae lobortis est mi at libero. Donec imperdiet elit nec quam iaculis, eu vehicula diam lacinia. Nam lacinia ex et arcu tincidunt, et iaculis mi euismod.</p>`


  createDb() {
    const articles = [
      { id: 1, articleName: `Artificial Intelligence Was Supposed to Reduce Hiring Discrimination. It’s Already Backfiring.`, authorName: "Tonya Riley", organizationId: "22", organizationName: "Mother Jones", datePublished: new Date('January 3, 2019 06:00:00'), illumineScore: 82, articleLink: "https://www.motherjones.com/politics/2019/01/artificial-intelligence-was-supposed-to-reduce-hiring-discrimination-its-already-backfiring/", 
               articleSummary: `Tonya Riley shines a light on the growing practice of companies using Artificial Intelligence to assist with hiring decisions.`},
      { id: 2, articleName: `Powell Says a ‘Patient’ Fed Is Watching for Signs of Economic Weakness`, authorName: "Jim Tankersley and Binyamin Appelbaum", organizationId: "12", organizationName: "New York Times", datePublished: new Date('October 15, 2004 01:19:05'), illumineScore: 92, articleLink: "https://www.nytimes.com/2019/01/04/business/economy/jerome-powell-fed-reserve.html",
               articleSummary: `The authors discuss the Federal Reserve chairman Jerome Powell's current holding pattern strategy.` },
      { id: 3, articleName: 'Police: Homicides in Chicago down by nearly 100 in 2018', authorName: "Michael Tarm", organizationId: "17", organizationName: "Fox News", datePublished: new Date('January 2, 2019'), illumineScore: 70, articleLink: "https://www.foxnews.com/us/police-homicides-in-chicago-down-by-nearly-100-in-2018", 
               articleSummary: "The author reviews the facts surrounding the decline in Chicago's gun violence in 2018." },
      { id: 4, articleName: 'House Democrat reintroduces impeachment articles against Trump', authorName: "Jeremy Herb & Manu Raju", organizationId: "14", organizationName: "CNN", datePublished: 'January 3, 2019 13:15', illumineScore: 84, articleLink: "https://www.cnn.com/2019/01/03/politics/impeachment-house-democrats-brad-sherman-trump/index.html",
               articleSummary: `The authors discuss California Democrat Brad Sherman's reintroduction of impeachment proceedings against President Trump.` },
      { id: 5, articleName: 'Paul Whelan: Ex-US Marine held on suspicion of spying is UK citizen', authorName: "Winston Churchill", organizationId: "15", organizationName: "BBC", datePublished: 'January 4, 2019 21:14:35', illumineScore: 66, articleLink: "https://www.bbc.com/news/uk-46756996",
               articleSummary: `The correspondent recounts events from Paul Whelan's upbringing through his arrest by Russian authorities.`, },
      // { id: 6, articleName: 'Guide to Griefing', authorName: "Vizzini", organizationId: "19", organizationName: "The Atlantic", articleSummary: this.articleSummaryText,  datePublished: 'February 16, 2011 21:14:35', illumineScore: 67 },
      { id: 7, articleName: `Bernie Sanders' fans can't be allowed to poison another Democratic primary with personal attacks`, authorName: "David Brock", organizationId: "16", organizationName: "MSNBC", datePublished: 'January 3, 2019 11:22', illumineScore: 56 , articleLink: 'https://www.nbcnews.com/think/opinion/bernie-sanders-fans-can-t-be-allowed-poison-another-democratic-ncna953976', 
               articleSummary: `In this opinion piece, David Brock makes the case for why the Democratic Party should cut Bernie Sanders supporters less slack in the coming 2020 election cycle.`},
      { id: 8, articleName: 'Nancy Pelosi Elected Speaker of the House', authorName: "Matt Fuller", organizationId: "21", organizationName: "Huffington Post", datePublished: 'January 3, 2019 13:48', illumineScore: 65, articleLink: "https://www.huffingtonpost.com/entry/nancy-pelosi-speaker-house-vote-congress_us_5c2e4d43e4b0407e90897fe6", 
               articleSummary: `The author recounts journey from Speaker of the House to political wilderness and back again before describing what lies ahead.`,   },
      { id: 9, articleName: 'The Real Story of 2016', authorName: "Nate Silver", organizationId: "20", organizationName: "Five-Thirty-Eight", datePublished: 'January 19, 2017 11:01', illumineScore: 61, 
               articleLink: "https://fivethirtyeight.com/features/the-real-story-of-2016/",
               articleSummary: 'Nate Silver discusses what reporters and analysts got wrong in the days, weeks, and months leading up to the 2016 Presidential election.' },
      // { id: 10, articleName: 'Neon Demons', authorName: "Jane Austen", organizationId: "11", organizationName: "Reuters", articleSummary: this.articleSummaryText,  datePublished: 'June 18, 2015 21:14:35', illumineScore: 7 },
    ];
    const organizations = [
      { id: 11, name: 'Reuters', organizationScore: 70 },
      { id: 12, name: 'New York Times', organizationScore: 81 },
      { id: 13, name: 'Washington Post', organizationScore: 92 },
      { id: 14, name: 'CNN', organizationScore: 65 },
      { id: 15, name: 'BBC', organizationScore: 93 },
      { id: 16, name: 'MSNBC', organizationScore: 63 },
      { id: 17, name: 'Fox News', organizationScore: 51 },
      { id: 18, name: 'Wall Street Journal', organizationScore: 67 },
      { id: 19, name: 'The Atlantic', organizationScore: 85 },
      { id: 20, name: 'FiveThirtyEight', organizationScore: 80 },
      { id: 21, name: 'Huffington Post', organizationScore: 59 },
      { id: 22, name: 'Mother Jones', organizationScore: 85 },
      { id: 23, name: 'InfoWars', organizationScore: 26 },
      { id: 24, name: 'Associated Press', organizationScore: 64},
      { id: 25, name: 'The Daily Beast', organizationScore: 70},
      { id: 26, name: 'Al Jazeera', organizationScore: 61},
      { id: 27, name: 'Daily Kos', organizationScore: 45}

    ];
    const editorials = [
      { id: 26, editorialName: 'Project Illumine', authorName: "World Citizen", organizationName: "Project Illumine", datePublished: new Date('January 4, 2019 12:50:35'),
                text: `<p>When you hear the phrase "fake news", what comes to mind? Certainly the 2016 Presidential election (and the prolonged investigation into it) are likely first thoughts. How about Facebook's role in helping to proliferate false information?<p>
                <p>Although the means for transmitting it have grown increasingly sophisticated, at its core fake news is very simple. It is a <i>lie</i>. Or, usually, lies. And the thing with lies&mdash;just like any other statement or assertion&mdash;is that they can be verified, or fact-checked, or debunked.</p>
                <p>Of course, if it is so easy to reveal an untruth for what it is, then why is there still so much misinformation out there? To be fair, there are plenty of organizations out there that routinely fact check statements by elected officials and other entities. But it seems like there ought to be an easier way to point the average consume of news in the right direction.</p>
                <p>Now you might be wondering if people would even use such news rating resource. Why bother looking up "recommended" news articles and organizations when I can just read my favorite news blog, site, or even just turn on a cable news channel? My response to this is two-fold:</p>
                <ul>
                <li>First, if you are satisfied with the way you get your information and the quality of it, then maybe you do not need help in finding your news.</li>
                <li>Second, the question I would ask is: do you use reviews to help you decide where to spend your money? I'm referring to reading publications like Consumer Reports when it comes to buying a car, or visiting Metacritic when deciding whether a movie is worth your time and money.</li>
                </ul>
                <p>Project Illumine is dedicated to those who are hungry for more truthful and better quality news. If you have made it this far, chances are you already harbor some skepticism for "news" items that are appear in your Facebook feed or (possibly worse) arrive in your email inbox. Our task here is to <i>feed</i> that skepticism and provide a place where critical thinking can flourish.</p>
                <p>To accomplish this, we will first provide <a href="https://illumine.news/reviews"><b>reviews</b></a> of <a href="https://illumine.news/articles"><b>news articles</b></a> from a variety of organizations. We shall rate the articles based not just on how truthful they are, but also on how thoroughly they tackle their subjects (e.g. - how many sources are provided?). In this way we aim to encourage quality in journalism while still fighting fake news.</p>
                <p>Each review will be given a score, and as multiple reviews are collected for an article our algorithm will combine these ratings into a single <b>Illumine score</b> for said article.</p>
                <p>Similarly, we will track the performance of the <a href="https://illumine.news/organizations"><b>news organizations</b></a> whose articles we rate and provide a score to help provide a picture of how each one is doing.</p>
                <p>Lastly, we will provide additional editorials&mdash;like this one&mdash;to shed some light on the state of our efforts, along with other noteworthy news about news.</p>
                <p>Do remember that Project Illumine is merely a prototype at this stage&mdash;a possible vision of things to come&mdash;but we would love to hear your ideas.</p>
                <p>Sincerely,</p>
                <div><b>WC</b></div>
                <a href="mailto:illumine.news@gmail.com"><b>illumine.news@gmail.com</b></a>` },
                { id: 30, editorialName: 'Peer review in journalism', authorName: "Sir Isaac Newton", organizationName: "Trinity College", datePublished: 'June 18, 1670 21:14:35', 
                text: `<p>There is a matter of public discourse that I find most perplexing. And that is the apparent lack of a peer review system for articles published by journalists.</p>
                <p>To be fair, journalists make their coin by publishing articles that people want to read; and it's often whoever publishes first that sells the most copies. So it would be unrealistic for a journalist to hold off on publishing a work until after his piece has been fully vetted in a peer-review journal.</p>
                <p>That being said, currently the only line of defense for a reporter publishing something incorrect is his colleagues in the newsroom. (And one could imagine this problem being worse if, some day, a publication medium allowed writers to bypass such critical reviews).
                <p>So what I propose is this: journalists continue to publish articles reviewed by the colleagues with whom they work every day. But <i>additionally</i>, every writer should submit a copy of each article for peer review. In this way, articles can be peer-reviewed after the fact, and over time reputations&mdash;both positive and negative&mdash;can be established for both journalists and the news organizations which they represent.</p>
                <p>It would be even more divine if some day journalists did not even need to submit the articles, with the peer-review organizations finding them. Perhaps some sort of feudal search carried out by the lords of the domain. Oh well, one can only dream...</p>
                `},
                { id: 22, editorialName: 'How to spot fake news', authorName: "Zoe Barnes", organizationName: "Slugline", datePublished: new Date('October 15, 2011 01:19:05'), 
                text: `<p>I'm always looking for a good story, especially those that involve powerful people. But I would like to say I have learned to differentiate real news from the fake stuff. Here are a few rules to help you identify if news is fake: </p>
                <h5>Outrageous Claims</h5>
                <p>Does the author of the article make ridiculous claims? Adolf Hitler famously made use of the <i>große Lüge</i> or "big lie", because he believed that if a lie was "collossal" enough, people would have a hard time believing the idea was made up.</p>
                <p>Now, clearly not all fake news is as destructive as Hitler's propaganda turned out to be; but it's still worth mentioning as a cautionary tale. For a free press to help keep a democracy healthy, it is important that the public have the ability to distinguish truth from fact. These days the tools and forces that disseminate information&mdash;be it true or false&mdash;are much more powerful than those that would help to adjuticate its veracity. Project Illumine aims to help with this fact-checking process, but as a citizen in a world overwhelmed by information, you would do well to develop your own filters for truthfulness in the content that you consume.</p>
                <h5>Escalating Ridiculousness</h5>
                <p>This is related to the previous point. Sometimes an author will escalate the shock-value of his claims in order to stir up anger in his audience. But sometimes an author is engaging in satire. Unfortunately, the lines between false but incendiary writing and satire can be difficult to recognize. But the good news is that if you are having trouble making this distinction, odds are the piece you are reading is intentionally making false claims (be it for satire or some attempt to elicit strong responses from readers).</p>
                <h5>What is the source</h5>
                <p>If you're looking for factually accurate news, make sure that you get your news from a reliable source. Here at Project Illumine we rate <a href="https://illumine.news/organizations">news organizations</a> based on how good of a job they are doing in reporting actual facts. The higher the score, the more you can trust a news organization to give you information without twisting it to some end or another.</p>
                <h5>Are the author's claims verifiable?</h5>
                <p>But even if you're not sure about an organization (or we don't have a rating for it), you can still follow some steps to do your own fact checking. And all it takes is a Google search. That's right, although there is a lot of bad information out there, we also have access to more fact-checking resources than ever before&mdash;you just need to know to look for them. Chances are that if a false claim is made by an organization that gets even a moderate amount of traffic it will be debunked by fact-checkers within hours or even minutes.</p>`}, 
      { id: 23, editorialName: 'Becoming your own news critic', authorName: "Mary Shelley", organizationName: "Fox News", datePublished: new Date('June 27, 2016 21:14:35'), 
                text: `<p>At its core, news&mdash;well, news that is <i>trying</i> to be news&mdash;aims to present information to the reader about something that has happened, is happening, or will happen. In some cases, the author may present information in such a way as to distort the truth. If you suspect this is the case, you can use the techniques in Zoe Barnes' <a href="https://illumine.news/editorials/22">How to Spot Fake News</a> article to identify if the author is being truthful or not.</p>
                <p>However, in many other cases the author is indeed trying to provide an accurate accounting of events but may fall short. Here are some things to keep in mind as you are readin the news.</p>
                <h5>How well does the author identify her source(s)?</h5>
                <p>So let's say an author is trying to tell us about an event that has happened. For the sake of argument, let's suppose the event being reported is that some workers went on strike at a manufacturing plant. As the author is presenting information about the strike, is she quoting anyone? If so, who? The workers? Management? Union representatives? Ideally, if we are to have a fair appraisal of an event&mdash;especially one like this where there are competing interests&mdash;it is important that reporters provide a complete as possible of a picture of the event. More time given to one side over the others is one sign that an author is showing bias. But let's get back to that a bit later.</p>
                <p>It's important that sources should be listed in terms of quotations, but it is also critical that an author cites evidence to back up any claims that are not self-evident. For example, it is a lot more convincing if an article says "Sea levels rose 6 inches in 2018, according to the US Geological Survey" than it would be if the article simply asserted "Sea levels rose 6 inches in 2018" with no citation.</p>
                <h5>Is the author's bias affecting the quality of the article?</h5>
                <p>I should start by saying that some amount of bias is unavoidable when it comes to news. Each reporter is human and will accordingly have his or her own personal opinions on matters. So it takes a great writer to ensure this bias is contained (along with a news organization that also prioritizes minimizing the effect of bias).</p>
                <p>One thing to keep in mind here is that news is not just about reporting facts&mdash;often it also involves a writer trying to help the reader navigate facts. Let's suppose that I can make certain verifiable claims about the fictional strike I mentioned ealier. For example, "The average worker salary was $25 at the time of the strike" or "The CEO's salary was $2.5 million". As an author I could make these statements (though <i>shouldn't</i> make them unless I can cite where I got the information). An article's veracity will live or die by how well statements like these are researched. But right now it's somethin else I'm after.</p>
                <p>If I'm reading the article about the strike, I want to know who is in the right, and who is in the wrong, or if all sides have valid claims. The risk here for an author is that she might want to pick a winner, especially if it makes for a better read. But the opportunity is that the author can educate the public on an important issue. For great reporting involves not just recounting what happened or will happened, but why. </p>
                <h5>Separating What and Why</h5>
                <p>We have talked about how the aim of great news is to present the what and why, but I wanted to underscore the important of keeping these things separate. If an author intertwines a sequence of events on which she is reporting too much with what she <i>believes</i> caused them, then it can become difficult to separate fact from hypothesis.</p>
                <p>This is why I like it when an author or news organization explicitly separates reporting of the facts from his or her analysis of the situation. <a href="https://www.bbc.com/news/uk-46756996">This BBC article</a> is a great example of how the separation of reporting facts from the author's two cents helps the reader digest the information appropriately. We should always stay vigilant about any claims an author makes, but it is certainly nice to see such a clearly defined distinction between reporting of the facts and presenting of hypotheses.</p>
                `},
                { id: 21, editorialName: 'Warp verfication', authorName: "Jean-Luc Picard", organizationName: "United Federation of Planets", datePublished: new Date('December 17, 2387 03:24:00'),
                text: `<p>During my time as an officer in the Federation, I have seen many things. Red shirts dying for what often seemed like nothing. Teleportation gone horribly awry. But what I haven't seen is good journalism.</p>
                <p>This is why I have spent countless hours holed up in the captain's quarters meticulously cataloguing reports from across the galaxy. Do you want to know what I've found? The only constant in the galactic press is this: the truth is never consistently there. How do I know? Because <i>I</i> was there at the Battle of Maxia. <i>I</i> saw an android laugh for the first time. And <i>I</i> had to endure that turncoat Riker firing on the Borg ship that had captured me.</p>
                You ask who is most qualified to adjudicate the veracity of all these claims? 'Tis none none other than I, Jean-Luc Picard!
                My crew and I will visit every star system and record every event, sometimes before it happens.</p>`},
      { id: 24, editorialName: 'Dealing with trolls', authorName: "Jeanne d'Arc", organizationName: "CNN", datePublished: 'April 14, 1984 21:14:35', text: this.editorialText},
      { id: 25, editorialName: 'Help - my father reads InfoWars', authorName: "Alan Turing", organizationName: "BBC", datePublished: 'March 16, 1920 21:14:35', text: this.editorialText},
      { id: 27, editorialName: 'Access over truth', authorName: "Yekaterina Alekseyevna", organizationName: "MSNBC", datePublished: 'June 15, 2013 21:14:35', text: this.editorialText},
      { id: 28, editorialName: 'Echo chamber', authorName: "Jules Verne", organizationName: "CNN", datePublished: 'January 10, 2010 21:14:35', text: this.editorialText},
      { id: 29, editorialName: 'Beyond the news cycle', authorName: "Jean-Luc Picard", organizationName: "United Federation of Planets", datePublished: 'October 30, 2387 21:14:35', text: this.editorialText},
    ];
    const reviews = [
      { id: 31, articleId: 1, articleName: `Artificial Intelligence Was Supposed to Reduce Hiring Discrimination. It’s Already Backfiring.`, contributorId: 41, contributorName: 'Lee Adama', reviewScore: 82, 
                text: `<div>The author provides a sound analysis of the ways in Artificial Intelligence has already begun to impact hiring practices. Her interview of policy analyst Mirganda Bogen does a great deal to shed light on how the use of AI can be harmful or unfair.</div>
                <div>That being said, it would be nice to hear the side of those in the AI industry who are developing the software under discussion. I suspect that they would argue they are only solving HR problems that have been around for some time.</div>` },
      { id: 32, articleId: 2, articleName: `Powell Says a ‘Patient’ Fed Is Watching for Signs of Economic Weakness`, contributorId: 42, contributorName: 'Tyrion Lannister', reviewScore: 92, text: this.reviewTextGood },
      { id: 33, articleId: 3, articleName: 'Police: Homicides in Chicago down by nearly 100 in 2018', contributorId: 43, contributorName: 'Ellen Ripley', reviewScore: 68, 
                text: `<div>In this article, the author provides a straightforward review of the facts surrounding the decline in Chicago's gun violence in 2018.</div>
                <div>Although at times he does not always state, the source of the facts he is citing, Michael Tarm does appear to give a full accounting of what happened with gun violence in Chicago during the last year. It would have been nice to get a deeper dive analyzing the causal link (or lack thereof) between the hiring of more officers, use of technology, and the decrease in gun crimes; but for better or worse this article was not quite that ambitious</div>` },
      { id: 34, articleId: 4, articleName: 'House Democrat reintroduces impeachment articles against Trump', contributorId: 44, contributorName: 'Richard Kiel', reviewScore: 85, 
                text: `Jeremy Herb and Manu Raju do a solid job of presenting the facts in this article. In addition to quoting Representative Brad Sherman, the authors also included statements from incoming Representatives Adam Smith and Jerry Nadler, both of which add depth to the report.` },
      { id: 35, articleId: 5, articleName: `Paul Whelan: Ex-US Marine held on suspicion of spying is UK citizen`, contributorId: 45, contributorName: 'Vizzini', reviewScore: 45, text: this.reviewTextBad },
      { id: 36, articleId: 5, articleName: `Paul Whelan: Ex-US Marine held on suspicion of spying is UK citizen`, contributorId: 46, contributorName: 'Lisbeth Salander', reviewScore: 86, text: this.reviewTextGood },
      { id: 37, articleId: 7, articleName: `Bernie Sanders' fans can't be allowed to poison another Democratic primary with personal attacks`, contributorId: 47, contributorName: 'Walter Cronkite', reviewScore: 56, 
                text: `<div>As an opinion piece on avoiding the repeat of past mistakes by the Democratic Party, this article falls flat save for some valid points.</div>
                <div>First, the author starts with a "Guess Who Said It!" game that challenges readers to distinguish Bernie Sanders quotes from Donald Trump ones. Although the intent of the exercise seems pretty clearly aimed at showing how low Sanders was willing to go to win; it seems rather unlikely that any of these statements did serious damage to the Sanders campaign in 2016. What's more, the author does not even follow-up with the statements, instead transitioning to (for the rest of the article) discuss Beto Rourke as the rightful (?) candidate to be protected from Sanders supporters as we approach 2020.</div>
                <div>And it is with the aim of protecting the author's apparent chosen golden boy in O'Rourke that the rest of the article devolves into suggesting possible ways of controlling a large electronic mob of Bernie supporters.</div>
                <div>If that is your biggest problem as a political party, haven't you already lost?</div>` },
      { id: 38, articleId: 8, articleName: 'Nancy Pelosi Elected Speaker of the House', contributorId: 48, contributorName: 'Don Collier', reviewScore: 65, 
                text: `<div>Although the author provides a decent summary describing Nancy Pelosi's path reclaiming the Speaker of the House position, he leaves some desirable details out. For instance, who are the "freshman Democrats [that] made promises during the campaign to not support Pelosi [for Speaker]"?</div>
                <div>Shortly thereafter, the author mentions how [Pelosi] was "able to frame the opposition [to her] as misogynist". Unfortunately he provides no evidence to back up this claim.</div>
                <div>To his credit the author does describe some of the dealmaking in which Pelosi engaged during her campaign for Speakership, such as promising the return of an election-centric committee and its chairwomanship to Rep. Marcia Fudge in return for her vote.</div>` },
      { id: 39, articleId: 9, articleName: 'The Real Story of 2016', contributorId: 49, contributorName: 'Clare Underwood', reviewScore: 43, 
                text: "Of course Nate would defend the integrity of the October and November polls across America. For were he to cast doubt upon them, the entire enterprise of data analytics would be called into question, dooming his circus of numbers..." },
      { id: 41, articleId: 9, articleName: 'The Real Story of 2016', contributorId: 49, contributorName: 'Edward Meechum', reviewScore: 79, 
                text: "I uh *gulp* agree with Clare about Nate's fears. But the man was always kind to me in his reviews of my field work. So I am giving him a decent score on this..." }
    ]

    return { articles, organizations, editorials, reviews };
  }
}